# docker-compose.yaml
version: '3.8'

services:

  goals-frontend:
    image: goals-frontend:1.0.0
    container_name: goals-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - https
    ports:
      - 3000:80
    env_file:
      - .env

networks:
  https:
    external:
      name: https_network

volumes:
  dbdata:
